kind: Service
apiVersion: v1
metadata:
  name: istio-deployment
  labels:
    app: istio
spec:
  selector:
    app: istio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-deployment
  labels:
    app: istio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: istio
  template:
    metadata:
      labels:
        app: istio
    spec:
      serviceAccountName: istio-csi-driver-deployment-sa
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "istio-deployment-aws-secrets"
      containers:
      - name: istio-deployment
        image: istio
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true

